ToDoApp/ToDoApp/Models/Duty.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoApp.Models
{
    public class Duty
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; } =string.Empty;
        public string Description { get; set; }
        public int? CategoryId { get; set; }
        public Category? Category { get; set; }

       [Column(TypeName = "nvarchar(20)")]
        public Priority? Priority { get; set; } 
       [Column(TypeName = "nvarchar(20)")]
        public Status? Status { get; set; }

        public TimeSpan?  Duration { get; set; }

        public DateTime DueDate { get; set; }
    }
}

ToDoApp/ToDoApp/Controllers/DutyController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Models;
using ToDoApp.Utilities;
using ToDoApp.Models.Repositories;
using ToDoApp.Utilities;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDoApp.ModelView;

namespace ToDoApp.Controllers
{
    public class DutyController : Controller
    {
        private readonly IDutyRepository _dutyrepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPriorityRepository _priorityRepository;
        private readonly IStatusRepository _statusRepository;
      
        public DutyController(IDutyRepository repository, ICategoryRepository categoryRepository, IPriorityRepository priorityRepository, IStatusRepository statusRepository)
        {
            _dutyrepository = repository;
            _categoryRepository = categoryRepository;
            _priorityRepository = priorityRepository;
            _statusRepository = statusRepository;
        }
        int PageSize = 5;
        public async Task<IActionResult> PagedIndex(int? pageNumeber)
        { var duties = await _dutyrepository.GetDutiesPaged(pageNumeber,PageSize);
            pageNumeber ??= 1;
            var count = await _dutyrepository.GetAllPiesCountAsync();

            return View( new PagedList<Duty>(duties.ToList(), pageNumeber.Value, count));
        }


        public async Task<IActionResult>Add ()
        {
            try
            {
                IEnumerable<Category>? categories = await _categoryRepository.GetCategories();
                IEnumerable<SelectListItem> selectListItems = new SelectList(categories, "Id", "Name", null);
                DutyViewModel duties = new DutyViewModel
                {
                    Categories = selectListItems,

                };
                return View(duties);

            }
            catch(Exception ex)
           
            {
                ViewData["ErrorMessage"] = $"An error occurred while processing your request:{ex}";
            }

            return View(new DutyViewModel() );
        }

        [HttpPost]
        public async Task<IActionResult> Add(DutyViewModel dutyViewModel)
        {
            Duty duty = new()
            {
                CategoryId = dutyViewModel?.Duty?.CategoryId,
                Title = dutyViewModel?.Duty?.Title ?? string.Empty,
                Description = dutyViewModel?.Duty?.Description ?? string.Empty,
                Priority = dutyViewModel?.Duty?.Priority,
                Status = dutyViewModel?.Duty?.Status,
                Duration = dutyViewModel?.Duty?.Duration,
                DueDate = dutyViewModel?.Duty?.DueDate ?? DateTime.Now
            };
            await _dutyrepository.Add(duty);
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoApp/ToDoApp/Views/Duty/Add.cshtml
@model DutyViewModel

<h2>You want a duty</h2>
<hr />


<form asp-action="Add" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div>
        <label asp-for="Duty.Title"></label>
        <input asp-for="Duty.Title" />
        <span asp-validation-for="Duty.Title"></span>
    </div>

    <div>
        <label asp-for="Duty.Description"></label>
        <textarea asp-for="Duty.Description"></textarea>
        <span asp-validation-for="Duty.Description"></span>
    </div>

    <div>
        <label asp-for="Duty.CategoryId"></label>
        <select asp-for="Duty.CategoryId" asp-items="@Model.Categories">
            <option value="">Select Category</option>
        </select>
        <span asp-validation-for="Duty.CategoryId"></span>
    </div>

    <div>
        <label asp-for="Duty.Priority"></label>
        <select asp-for="Duty.Priority" asp-items="@Model.Priorities">
            <option value="">Select Priority</option>
        </select>
        <span asp-validation-for="Duty.Priority"></span>
    </div>

    <div>
        <label asp-for="Duty.Status"></label>
        <select asp-for="Duty.Status" asp-items="@Model.Statuses">
            <option value="">Select Status</option>
        </select>
        <span asp-validation-for="Duty.Status"></span>
    </div>

    <div>
        <label asp-for="Duty.Duration"></label>
        <input asp-for="Duty.Duration" type="time" />
        <span asp-validation-for="Duty.Duration"></span>
    </div>

    <div>
        <label asp-for="Duty.DueDate"></label>
        <input asp-for="Duty.DueDate" type="date" />
        <span asp-validation-for="Duty.DueDate"></span>
    </div>
    <input type="submit" value="Add category"  />



    </form>

ToDoApp/ToDoApp/Views/Duty/Index.cshtml
@model IEnumerable<Duty>
<h2>Duties</h2>
<hr />
@if(!Model.Any())
{
    <h3>No duties found</h3>
}
else
{
    <table>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Priority</th>
            <th>Duration</th>
            <th>Due Date</th>
        </tr>
        @foreach (var duty in Model)
        {
            <tr>
                <td>@duty.Id</td>
                <td>@duty.Title</td>
                <td>@duty.Description</td>
                <td>@duty.Status</td>
                <td>@duty.Priority</td>
                <td>@duty.Duration</td>
                <td>@duty.DueDate</td>
            </tr>
        }

    </table>
}
<a asp-controller="Duty" asp-action="Index">Add</a>

ToDoApp/ToDoApp/Views/Duty/PagedIndex.cshtml
@using ToDoApp.Utilities;
@model PagedList<Duty>


<h2>Duties</h2>
<hr />
@if(!Model.Any())
{
    <h3>No duties found</h3>
}
else
{
    <table>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Priority</th>
            <th>Duration</th>
            <th>Due Date</th>
        </tr>
        @foreach (var duty in Model)
        {
            <tr>
                <td>@duty.Id</td>
                <td>@duty.Title</td>
                <td>@duty.Description</td>
                <td>@duty.Status</td>
                <td>@duty.Priority</td>
                <td>@duty.Duration</td>
                <td>@duty.DueDate</td>
            </tr>
        }

    </table>
}
@{
    var previousButtonDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextButtonDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="IndexPaging" asp-route-pageNumber="@(Model.PageIndex - 1)" class="btn btn-default @previousButtonDisabled">
    Previous
</a>
<a asp-action="IndexPaging" asp-route-pageNumber="@(Model.PageIndex + 1)" class="btn btn-default @nextButtonDisabled">
    Next
</a>


<p>
    <a class="btn btn-primary" asp-action="Add">Add new pie</a>
</p>

<a asp-controller="Duty" asp-action="Index">Add</a>